development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: study_db
 pool: 5
 username: root
 password:

test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: study_db_test
 pool: 5
 username: root
 password:
# socket: /var/lib/mysql/mysql.sock

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: study_db_production
 pool: 50
 username: root
 password:
